export const countryListFr = [
  { label: "--Sélectionnez un pays--", value: -1, iso: "" },
  { label: "Afghanistan", value: 1, iso: "AF" },
  { label: "Afrique du Sud", value: 2, iso: "ZA" },
  { label: "Albanie", value: 3, iso: "AL" },
  { label: "Algérie", value: 4, iso: "DZ" },
  { label: "Allemagne", value: 5, iso: "DE" },
  { label: "Andorre", value: 6, iso: "AD" },
  { label: "Angola", value: 7, iso: "AO" },
  { label: "Antigua-et-Barbuda", value: 8, iso: "AG" },
  { label: "Arabie saoudite", value: 9, iso: "SA" },
  { label: "Argentine", value: 10, iso: "AR" },
  { label: "Arménie", value: 11, iso: "AM" },
  { label: "Australie", value: 12, iso: "AU" },
  { label: "Autriche", value: 13, iso: "AT" },
  { label: "Azerbaïdjan", value: 14, iso: "AZ" },
  { label: "Bahamas", value: 15, iso: "BS" },
  { label: "Bahreïn", value: 16, iso: "BH" },
  { label: "Bangladesh", value: 17, iso: "BD" },
  { label: "Barbade", value: 18, iso: "BB" },
  { label: "Belgique", value: 19, iso: "BE" },
  { label: "Belize", value: 20, iso: "BZ" },
  { label: "Bénin", value: 21, iso: "BJ" },
  { label: "Bhoutan", value: 22, iso: "BT" },
  { label: "Biélorussie", value: 23, iso: "BY" },
  { label: "Bolivie", value: 24, iso: "BO" },
  { label: "Bosnie-Herzégovine", value: 25, iso: "BA" },
  { label: "Botswana", value: 26, iso: "BW" },
  { label: "Brésil", value: 27, iso: "BR" },
  { label: "Brunei", value: 28, iso: "BN" },
  { label: "Bulgarie", value: 29, iso: "BG" },
  { label: "Burkina Faso", value: 30, iso: "BF" },
  { label: "Burundi", value: 31, iso: "BI" },
  { label: "Cambodge", value: 32, iso: "KH" },
  { label: "Cameroun", value: 33, iso: "CM" },
  { label: "Canada", value: 34, iso: "CA" },
  { label: "Cap-Vert", value: 35, iso: "CV" },
  { label: "Chili", value: 36, iso: "CL" },
  { label: "Chine", value: 37, iso: "CN" },
  { label: "Chypre", value: 38, iso: "CY" },
  { label: "Colombie", value: 39, iso: "CO" },
  { label: "Comores", value: 40, iso: "KM" },
  { label: "Congo", value: 41, iso: "CG" },
  { label: "Congo (République démocratique du)", value: 42, iso: "CD" },
  { label: "Corée du Nord", value: 43, iso: "KP" },
  { label: "Corée du Sud", value: 44, iso: "KR" },
  { label: "Costa Rica", value: 45, iso: "CR" },
  { label: "Côte d’Ivoire", value: 46, iso: "CI" },
  { label: "Croatie", value: 47, iso: "HR" },
  { label: "Cuba", value: 48, iso: "CU" },
  { label: "Danemark", value: 49, iso: "DK" },
  { label: "Djibouti", value: 50, iso: "DJ" },
  { label: "Dominique", value: 51, iso: "DM" },
  { label: "Égypte", value: 52, iso: "EG" },
  { label: "Émirats arabes unis", value: 53, iso: "AE" },
  { label: "Équateur", value: 54, iso: "EC" },
  { label: "Érythrée", value: 55, iso: "ER" },
  { label: "Espagne", value: 56, iso: "ES" },
  { label: "Estonie", value: 57, iso: "EE" },
  { label: "Eswatini", value: 58, iso: "SZ" },
  { label: "États-Unis", value: 59, iso: "US" },
  { label: "Éthiopie", value: 60, iso: "ET" },
  { label: "Fidji", value: 61, iso: "FJ" },
  { label: "Finlande", value: 62, iso: "FI" },
  { label: "France", value: 63, iso: "FR" },
  { label: "Gabon", value: 64, iso: "GA" },
  { label: "Gambie", value: 65, iso: "GM" },
  { label: "Géorgie", value: 66, iso: "GE" },
  { label: "Ghana", value: 67, iso: "GH" },
  { label: "Grèce", value: 68, iso: "GR" },
  { label: "Grenade", value: 69, iso: "GD" },
  { label: "Guatemala", value: 70, iso: "GT" },
  { label: "Guinée", value: 71, iso: "GN" },
  { label: "Guinée-Bissau", value: 72, iso: "GW" },
  { label: "Guinée équatoriale", value: 73, iso: "GQ" },
  { label: "Guyana", value: 74, iso: "GY" },
  { label: "Haïti", value: 75, iso: "HT" },
  { label: "Honduras", value: 76, iso: "HN" },
  { label: "Hongrie", value: 77, iso: "HU" },
  { label: "Îles Marshall", value: 78, iso: "MH" },
  { label: "Îles Salomon", value: 79, iso: "SB" },
  { label: "Inde", value: 80, iso: "IN" },
  { label: "Indonésie", value: 81, iso: "ID" },
  { label: "Irak", value: 82, iso: "IQ" },
  { label: "Iran", value: 83, iso: "IR" },
  { label: "Irlande", value: 84, iso: "IE" },
  { label: "Islande", value: 85, iso: "IS" },
  { label: "Israël", value: 86, iso: "IL" },
  { label: "Italie", value: 87, iso: "IT" },
  { label: "Jamaïque", value: 88, iso: "JM" },
  { label: "Japon", value: 89, iso: "JP" },
  { label: "Jordanie", value: 90, iso: "JO" },
  { label: "Kazakhstan", value: 91, iso: "KZ" },
  { label: "Kenya", value: 92, iso: "KE" },
  { label: "Kirghizistan", value: 93, iso: "KG" },
  { label: "Kiribati", value: 94, iso: "KI" },
  { label: "Koweït", value: 95, iso: "KW" },
  { label: "Laos", value: 96, iso: "LA" },
  { label: "Lesotho", value: 97, iso: "LS" },
  { label: "Lettonie", value: 98, iso: "LV" },
  { label: "Liban", value: 99, iso: "LB" },
  { label: "Liberia", value: 100, iso: "LR" },
  { label: "Libye", value: 101, iso: "LY" },
  { label: "Liechtenstein", value: 102, iso: "LI" },
  { label: "Lituanie", value: 103, iso: "LT" },
  { label: "Luxembourg", value: 104, iso: "LU" },
  { label: "Macédoine du Nord", value: 105, iso: "MK" },
  { label: "Madagascar", value: 106, iso: "MG" },
  { label: "Malaisie", value: 107, iso: "MY" },
  { label: "Malawi", value: 108, iso: "MW" },
  { label: "Maldives", value: 109, iso: "MV" },
  { label: "Mali", value: 110, iso: "ML" },
  { label: "Malte", value: 111, iso: "MT" },
  { label: "Maroc", value: 112, iso: "MA" },
  { label: "Maurice", value: 113, iso: "MU" },
  { label: "Mauritanie", value: 114, iso: "MR" },
  { label: "Mexique", value: 115, iso: "MX" },
  { label: "Micronésie", value: 116, iso: "FM" },
  { label: "Moldavie", value: 117, iso: "MD" },
  { label: "Monaco", value: 118, iso: "MC" },
  { label: "Mongolie", value: 119, iso: "MN" },
  { label: "Monténégro", value: 120, iso: "ME" },
  { label: "Mozambique", value: 121, iso: "MZ" },
  { label: "Myanmar", value: 122, iso: "MM" },
  { label: "Namibie", value: 123, iso: "NA" },
  { label: "Nauru", value: 124, iso: "NR" },
  { label: "Népal", value: 125, iso: "NP" },
  { label: "Nicaragua", value: 126, iso: "NI" },
  { label: "Niger", value: 127, iso: "NE" },
  { label: "Nigéria", value: 128, iso: "NG" },
  { label: "Norvège", value: 129, iso: "NO" },
  { label: "Nouvelle-Zélande", value: 130, iso: "NZ" },
  { label: "Oman", value: 131, iso: "OM" },
  { label: "Ouganda", value: 132, iso: "UG" },
  { label: "Ouzbékistan", value: 133, iso: "UZ" },
  { label: "Pakistan", value: 134, iso: "PK" },
  { label: "Palaos", value: 135, iso: "PW" },
  { label: "Panama", value: 136, iso: "PA" },
  { label: "Papouasie-Nouvelle-Guinée", value: 137, iso: "PG" },
  { label: "Paraguay", value: 138, iso: "PY" },
  { label: "Pays-Bas", value: 139, iso: "NL" },
  { label: "Pérou", value: 140, iso: "PE" },
  { label: "Philippines", value: 141, iso: "PH" },
  { label: "Pologne", value: 142, iso: "PL" },
  { label: "Portugal", value: 143, iso: "PT" },
  { label: "Qatar", value: 144, iso: "QA" },
  { label: "République centrafricaine", value: 145, iso: "CF" },
  { label: "République dominicaine", value: 146, iso: "DO" },
  { label: "République tchèque", value: 147, iso: "CZ" },
  { label: "Roumanie", value: 148, iso: "RO" },
  { label: "Royaume-Uni", value: 149, iso: "GB" },
  { label: "Russie", value: 150, iso: "RU" },
  { label: "Rwanda", value: 151, iso: "RW" },
  { label: "Saint-Kitts-et-Nevis", value: 152, iso: "KN" },
  { label: "Saint-Marin", value: 153, iso: "SM" },
  { label: "Saint-Vincent-et-les-Grenadines", value: 154, iso: "VC" },
  { label: "Sainte-Lucie", value: 155, iso: "LC" },
  { label: "Salvador", value: 156, iso: "SV" },
  { label: "Samoa", value: 157, iso: "WS" },
  { label: "Sao Tomé-et-Principe", value: 158, iso: "ST" },
  { label: "Sénégal", value: 159, iso: "SN" },
  { label: "Serbie", value: 160, iso: "RS" },
  { label: "Seychelles", value: 161, iso: "SC" },
  { label: "Sierra Leone", value: 162, iso: "SL" },
  { label: "Singapour", value: 163, iso: "SG" },
  { label: "Slovaquie", value: 164, iso: "SK" },
  { label: "Slovénie", value: 165, iso: "SI" },
  { label: "Somalie", value: 166, iso: "SO" },
  { label: "Soudan", value: 167, iso: "SD" },
  { label: "Soudan du Sud", value: 168, iso: "SS" },
  { label: "Sri Lanka", value: 169, iso: "LK" },
  { label: "Suède", value: 170, iso: "SE" },
  { label: "Suisse", value: 171, iso: "CH" },
  { label: "Suriname", value: 172, iso: "SR" },
  { label: "Syrie", value: 173, iso: "SY" },
  { label: "Tadjikistan", value: 174, iso: "TJ" },
  { label: "Tanzanie", value: 175, iso: "TZ" },
  { label: "Tchad", value: 176, iso: "TD" },
  { label: "Thaïlande", value: 177, iso: "TH" },
  { label: "Timor oriental", value: 178, iso: "TL" },
  { label: "Togo", value: 179, iso: "TG" },
  { label: "Tonga", value: 180, iso: "TO" },
  { label: "Trinité-et-Tobago", value: 181, iso: "TT" },
  { label: "Tunisie", value: 182, iso: "TN" },
  { label: "Turkménistan", value: 183, iso: "TM" },
  { label: "Turquie", value: 184, iso: "TR" },
  { label: "Tuvalu", value: 185, iso: "TV" },
  { label: "Ukraine", value: 186, iso: "UA" },
  { label: "Uruguay", value: 187, iso: "UY" },
  { label: "Vanuatu", value: 188, iso: "VU" },
  { label: "Vatican", value: 189, iso: "VA" },
  { label: "Venezuela", value: 190, iso: "VE" },
  { label: "Viêt Nam", value: 191, iso: "VN" },
  { label: "Yémen", value: 192, iso: "YE" },
  { label: "Zambie", value: 193, iso: "ZM" },
  { label: "Zimbabwe", value: 194, iso: "ZW" },
];

export const countryListEn = [
  { label: "--Select a country--", value: -1, iso: "" },
  { label: "Afghanistan", value: 1, iso: "AF" },
  { label: "South Africa", value: 2, iso: "ZA" },
  { label: "Albania", value: 3, iso: "AL" },
  { label: "Algeria", value: 4, iso: "DZ" },
  { label: "Germany", value: 5, iso: "DE" },
  { label: "Andorra", value: 6, iso: "AD" },
  { label: "Angola", value: 7, iso: "AO" },
  { label: "Antigua and Barbuda", value: 8, iso: "AG" },
  { label: "Saudi Arabia", value: 9, iso: "SA" },
  { label: "Argentina", value: 10, iso: "AR" },
  { label: "Armenia", value: 11, iso: "AM" },
  { label: "Australia", value: 12, iso: "AU" },
  { label: "Austria", value: 13, iso: "AT" },
  { label: "Azerbaijan", value: 14, iso: "AZ" },
  { label: "Bahamas", value: 15, iso: "BS" },
  { label: "Bahrain", value: 16, iso: "BH" },
  { label: "Bangladesh", value: 17, iso: "BD" },
  { label: "Barbados", value: 18, iso: "BB" },
  { label: "Belgium", value: 19, iso: "BE" },
  { label: "Belize", value: 20, iso: "BZ" },
  { label: "Benin", value: 21, iso: "BJ" },
  { label: "Bhutan", value: 22, iso: "BT" },
  { label: "Belarus", value: 23, iso: "BY" },
  { label: "Bolivia", value: 24, iso: "BO" },
  { label: "Bosnia and Herzegovina", value: 25, iso: "BA" },
  { label: "Botswana", value: 26, iso: "BW" },
  { label: "Brazil", value: 27, iso: "BR" },
  { label: "Brunei", value: 28, iso: "BN" },
  { label: "Bulgaria", value: 29, iso: "BG" },
  { label: "Burkina Faso", value: 30, iso: "BF" },
  { label: "Burundi", value: 31, iso: "BI" },
  { label: "Cambodia", value: 32, iso: "KH" },
  { label: "Cameroon", value: 33, iso: "CM" },
  { label: "Canada", value: 34, iso: "CA" },
  { label: "Cape Verde", value: 35, iso: "CV" },
  { label: "Chile", value: 36, iso: "CL" },
  { label: "China", value: 37, iso: "CN" },
  { label: "Cyprus", value: 38, iso: "CY" },
  { label: "Colombia", value: 39, iso: "CO" },
  { label: "Comoros", value: 40, iso: "KM" },
  { label: "Republic of the Congo", value: 41, iso: "CG" },
  { label: "Democratic Republic of the Congo", value: 42, iso: "CD" },
  { label: "North Korea", value: 43, iso: "KP" },
  { label: "South Korea", value: 44, iso: "KR" },
  { label: "Costa Rica", value: 45, iso: "CR" },
  { label: "Ivory Coast", value: 46, iso: "CI" },
  { label: "Croatia", value: 47, iso: "HR" },
  { label: "Cuba", value: 48, iso: "CU" },
  { label: "Denmark", value: 49, iso: "DK" },
  { label: "Djibouti", value: 50, iso: "DJ" },
  { label: "Dominica", value: 51, iso: "DM" },
  { label: "Egypt", value: 52, iso: "EG" },
  { label: "United Arab Emirates", value: 53, iso: "AE" },
  { label: "Ecuador", value: 54, iso: "EC" },
  { label: "Eritrea", value: 55, iso: "ER" },
  { label: "Spain", value: 56, iso: "ES" },
  { label: "Estonia", value: 57, iso: "EE" },
  { label: "Eswatini", value: 58, iso: "SZ" },
  { label: "United States", value: 59, iso: "US" },
  { label: "Ethiopia", value: 60, iso: "ET" },
  { label: "Fiji", value: 61, iso: "FJ" },
  { label: "Finland", value: 62, iso: "FI" },
  { label: "France", value: 63, iso: "FR" },
  { label: "Gabon", value: 64, iso: "GA" },
  { label: "Gambia", value: 65, iso: "GM" },
  { label: "Georgia", value: 66, iso: "GE" },
  { label: "Ghana", value: 67, iso: "GH" },
  { label: "Greece", value: 68, iso: "GR" },
  { label: "Grenada", value: 69, iso: "GD" },
  { label: "Guatemala", value: 70, iso: "GT" },
  { label: "Guinea", value: 71, iso: "GN" },
  { label: "Guinea-Bissau", value: 72, iso: "GW" },
  { label: "Equatorial Guinea", value: 73, iso: "GQ" },
  { label: "Guyana", value: 74, iso: "GY" },
  { label: "Haiti", value: 75, iso: "HT" },
  { label: "Honduras", value: 76, iso: "HN" },
  { label: "Hungary", value: 77, iso: "HU" },
  { label: "Marshall Islands", value: 78, iso: "MH" },
  { label: "Solomon Islands", value: 79, iso: "SB" },
  { label: "India", value: 80, iso: "IN" },
  { label: "Indonesia", value: 81, iso: "ID" },
  { label: "Iraq", value: 82, iso: "IQ" },
  { label: "Iran", value: 83, iso: "IR" },
  { label: "Ireland", value: 84, iso: "IE" },
  { label: "Iceland", value: 85, iso: "IS" },
  { label: "Israel", value: 86, iso: "IL" },
  { label: "Italy", value: 87, iso: "IT" },
  { label: "Jamaica", value: 88, iso: "JM" },
  { label: "Japan", value: 89, iso: "JP" },
  { label: "Jordan", value: 90, iso: "JO" },
  { label: "Kazakhstan", value: 91, iso: "KZ" },
  { label: "Kenya", value: 92, iso: "KE" },
  { label: "Kyrgyzstan", value: 93, iso: "KG" },
  { label: "Kiribati", value: 94, iso: "KI" },
  { label: "Kuwait", value: 95, iso: "KW" },
  { label: "Laos", value: 96, iso: "LA" },
  { label: "Lesotho", value: 97, iso: "LS" },
  { label: "Latvia", value: 98, iso: "LV" },
  { label: "Lebanon", value: 99, iso: "LB" },
  { label: "Liberia", value: 100, iso: "LR" },
  { label: "Libya", value: 101, iso: "LY" },
  { label: "Liechtenstein", value: 102, iso: "LI" },
  { label: "Lithuania", value: 103, iso: "LT" },
  { label: "Luxembourg", value: 104, iso: "LU" },
  { label: "North Macedonia", value: 105, iso: "MK" },
  { label: "Madagascar", value: 106, iso: "MG" },
  { label: "Malaysia", value: 107, iso: "MY" },
  { label: "Malawi", value: 108, iso: "MW" },
  { label: "Maldives", value: 109, iso: "MV" },
  { label: "Mali", value: 110, iso: "ML" },
  { label: "Malta", value: 111, iso: "MT" },
  { label: "Morocco", value: 112, iso: "MA" },
  { label: "Mauritius", value: 113, iso: "MU" },
  { label: "Mauritania", value: 114, iso: "MR" },
  { label: "Mexico", value: 115, iso: "MX" },
  { label: "Micronesia", value: 116, iso: "FM" },
  { label: "Moldova", value: 117, iso: "MD" },
  { label: "Monaco", value: 118, iso: "MC" },
  { label: "Mongolia", value: 119, iso: "MN" },
  { label: "Montenegro", value: 120, iso: "ME" },
  { label: "Mozambique", value: 121, iso: "MZ" },
  { label: "Myanmar", value: 122, iso: "MM" },
  { label: "Namibia", value: 123, iso: "NA" },
  { label: "Nauru", value: 124, iso: "NR" },
  { label: "Nepal", value: 125, iso: "NP" },
  { label: "Nicaragua", value: 126, iso: "NI" },
  { label: "Niger", value: 127, iso: "NE" },
  { label: "Nigeria", value: 128, iso: "NG" },
  { label: "Norway", value: 129, iso: "NO" },
  { label: "New Zealand", value: 130, iso: "NZ" },
  { label: "Oman", value: 131, iso: "OM" },
  { label: "Uganda", value: 132, iso: "UG" },
  { label: "Uzbekistan", value: 133, iso: "UZ" },
  { label: "Pakistan", value: 134, iso: "PK" },
  { label: "Palau", value: 135, iso: "PW" },
  { label: "Panama", value: 136, iso: "PA" },
  { label: "Papua New Guinea", value: 137, iso: "PG" },
  { label: "Paraguay", value: 138, iso: "PY" },
  { label: "Netherlands", value: 139, iso: "NL" },
  { label: "Peru", value: 140, iso: "PE" },
  { label: "Philippines", value: 141, iso: "PH" },
  { label: "Poland", value: 142, iso: "PL" },
  { label: "Portugal", value: 143, iso: "PT" },
  { label: "Qatar", value: 144, iso: "QA" },
  { label: "Central African Republic", value: 145, iso: "CF" },
  { label: "Dominican Republic", value: 146, iso: "DO" },
  { label: "Czech Republic", value: 147, iso: "CZ" },
  { label: "Romania", value: 148, iso: "RO" },
  { label: "United Kingdom", value: 149, iso: "GB" },
  { label: "Russia", value: 150, iso: "RU" },
  { label: "Rwanda", value: 151, iso: "RW" },
  { label: "Saint Kitts and Nevis", value: 152, iso: "KN" },
  { label: "San Marino", value: 153, iso: "SM" },
  { label: "Saint Vincent and the Grenadines", value: 154, iso: "VC" },
  { label: "Saint Lucia", value: 155, iso: "LC" },
  { label: "El Salvador", value: 156, iso: "SV" },
  { label: "Samoa", value: 157, iso: "WS" },
  { label: "Sao Tome and Principe", value: 158, iso: "ST" },
  { label: "Senegal", value: 159, iso: "SN" },
  { label: "Serbia", value: 160, iso: "RS" },
  { label: "Seychelles", value: 161, iso: "SC" },
  { label: "Sierra Leone", value: 162, iso: "SL" },
  { label: "Singapore", value: 163, iso: "SG" },
  { label: "Slovakia", value: 164, iso: "SK" },
  { label: "Slovenia", value: 165, iso: "SI" },
  { label: "Somalia", value: 166, iso: "SO" },
  { label: "Sudan", value: 167, iso: "SD" },
  { label: "South Sudan", value: 168, iso: "SS" },
  { label: "Sri Lanka", value: 169, iso: "LK" },
  { label: "Sweden", value: 170, iso: "SE" },
  { label: "Switzerland", value: 171, iso: "CH" },
  { label: "Suriname", value: 172, iso: "SR" },
  { label: "Syria", value: 173, iso: "SY" },
  { label: "Tajikistan", value: 174, iso: "TJ" },
  { label: "Tanzania", value: 175, iso: "TZ" },
  { label: "Chad", value: 176, iso: "TD" },
  { label: "Thailand", value: 177, iso: "TH" },
  { label: "East Timor", value: 178, iso: "TL" },
  { label: "Togo", value: 179, iso: "TG" },
  { label: "Tonga", value: 180, iso: "TO" },
  { label: "Trinidad and Tobago", value: 181, iso: "TT" },
  { label: "Tunisia", value: 182, iso: "TN" },
  { label: "Turkmenistan", value: 183, iso: "TM" },
  { label: "Turkey", value: 184, iso: "TR" },
  { label: "Tuvalu", value: 185, iso: "TV" },
  { label: "Ukraine", value: 186, iso: "UA" },
  { label: "Uruguay", value: 187, iso: "UY" },
  { label: "Vanuatu", value: 188, iso: "VU" },
  { label: "Vatican City", value: 189, iso: "VA" },
  { label: "Venezuela", value: 190, iso: "VE" },
  { label: "Vietnam", value: 191, iso: "VN" },
  { label: "Yemen", value: 192, iso: "YE" },
  { label: "Zambia", value: 193, iso: "ZM" },
  { label: "Zimbabwe", value: 194, iso: "ZW" },
];
