export const countryListFr = [
  { label: "--Sélectionnez un pays--", value: -1 },
  { label: "Afghanistan", value: 1 },
  { label: "Afrique du Sud", value: 2 },
  { label: "Albanie", value: 3 },
  { label: "Algérie", value: 4 },
  { label: "Allemagne", value: 5 },
  { label: "Andorre", value: 6 },
  { label: "Angola", value: 7 },
  { label: "Antigua-et-Barbuda", value: 8 },
  { label: "Arabie saoudite", value: 9 },
  { label: "Argentine", value: 10 },
  { label: "Arménie", value: 11 },
  { label: "Australie", value: 12 },
  { label: "Autriche", value: 13 },
  { label: "Azerbaïdjan", value: 14 },
  { label: "Bahamas", value: 15 },
  { label: "Bahreïn", value: 16 },
  { label: "Bangladesh", value: 17 },
  { label: "Barbade", value: 18 },
  { label: "Belgique", value: 19 },
  { label: "Belize", value: 20 },
  { label: "Bénin", value: 21 },
  { label: "Bhoutan", value: 22 },
  { label: "Biélorussie", value: 23 },
  { label: "Bolivie", value: 24 },
  { label: "Bosnie-Herzégovine", value: 25 },
  { label: "Botswana", value: 26 },
  { label: "Brésil", value: 27 },
  { label: "Brunei", value: 28 },
  { label: "Bulgarie", value: 29 },
  { label: "Burkina Faso", value: 30 },
  { label: "Burundi", value: 31 },
  { label: "Cambodge", value: 32 },
  { label: "Cameroun", value: 33 },
  { label: "Canada", value: 34 },
  { label: "Cap-Vert", value: 35 },
  { label: "Chili", value: 36 },
  { label: "Chine", value: 37 },
  { label: "Chypre", value: 38 },
  { label: "Colombie", value: 39 },
  { label: "Comores", value: 40 },
  { label: "Congo", value: 41 },
  { label: "Congo (République démocratique du)", value: 42 },
  { label: "Corée du Nord", value: 43 },
  { label: "Corée du Sud", value: 44 },
  { label: "Costa Rica", value: 45 },
  { label: "Côte d’Ivoire", value: 46 },
  { label: "Croatie", value: 47 },
  { label: "Cuba", value: 48 },
  { label: "Danemark", value: 49 },
  { label: "Djibouti", value: 50 },
  { label: "Dominique", value: 51 },
  { label: "Égypte", value: 52 },
  { label: "Émirats arabes unis", value: 53 },
  { label: "Équateur", value: 54 },
  { label: "Érythrée", value: 55 },
  { label: "Espagne", value: 56 },
  { label: "Estonie", value: 57 },
  { label: "Eswatini", value: 58 },
  { label: "États-Unis", value: 59 },
  { label: "Éthiopie", value: 60 },
  { label: "Fidji", value: 61 },
  { label: "Finlande", value: 62 },
  { label: "France", value: 63 },
  { label: "Gabon", value: 64 },
  { label: "Gambie", value: 65 },
  { label: "Géorgie", value: 66 },
  { label: "Ghana", value: 67 },
  { label: "Grèce", value: 68 },
  { label: "Grenade", value: 69 },
  { label: "Guatemala", value: 70 },
  { label: "Guinée", value: 71 },
  { label: "Guinée-Bissau", value: 72 },
  { label: "Guinée équatoriale", value: 73 },
  { label: "Guyana", value: 74 },
  { label: "Haïti", value: 75 },
  { label: "Honduras", value: 76 },
  { label: "Hongrie", value: 77 },
  { label: "Îles Marshall", value: 78 },
  { label: "Îles Salomon", value: 79 },
  { label: "Inde", value: 80 },
  { label: "Indonésie", value: 81 },
  { label: "Irak", value: 82 },
  { label: "Iran", value: 83 },
  { label: "Irlande", value: 84 },
  { label: "Islande", value: 85 },
  { label: "Israël", value: 86 },
  { label: "Italie", value: 87 },
  { label: "Jamaïque", value: 88 },
  { label: "Japon", value: 89 },
  { label: "Jordanie", value: 90 },
  { label: "Kazakhstan", value: 91 },
  { label: "Kenya", value: 92 },
  { label: "Kirghizistan", value: 93 },
  { label: "Kiribati", value: 94 },
  { label: "Koweït", value: 95 },
  { label: "Laos", value: 96 },
  { label: "Lesotho", value: 97 },
  { label: "Lettonie", value: 98 },
  { label: "Liban", value: 99 },
  { label: "Liberia", value: 100 },
  { label: "Libye", value: 101 },
  { label: "Liechtenstein", value: 102 },
  { label: "Lituanie", value: 103 },
  { label: "Luxembourg", value: 104 },
  { label: "Macédoine du Nord", value: 105 },
  { label: "Madagascar", value: 106 },
  { label: "Malaisie", value: 107 },
  { label: "Malawi", value: 108 },
  { label: "Maldives", value: 109 },
  { label: "Mali", value: 110 },
  { label: "Malte", value: 111 },
  { label: "Maroc", value: 112 },
  { label: "Maurice", value: 113 },
  { label: "Mauritanie", value: 114 },
  { label: "Mexique", value: 115 },
  { label: "Micronésie", value: 116 },
  { label: "Moldavie", value: 117 },
  { label: "Monaco", value: 118 },
  { label: "Mongolie", value: 119 },
  { label: "Monténégro", value: 120 },
  { label: "Mozambique", value: 121 },
  { label: "Myanmar", value: 122 },
  { label: "Namibie", value: 123 },
  { label: "Nauru", value: 124 },
  { label: "Népal", value: 125 },
  { label: "Nicaragua", value: 126 },
  { label: "Niger", value: 127 },
  { label: "Nigéria", value: 128 },
  { label: "Norvège", value: 129 },
  { label: "Nouvelle-Zélande", value: 130 },
  { label: "Oman", value: 131 },
  { label: "Ouganda", value: 132 },
  { label: "Ouzbékistan", value: 133 },
  { label: "Pakistan", value: 134 },
  { label: "Palaos", value: 135 },
  { label: "Panama", value: 136 },
  { label: "Papouasie-Nouvelle-Guinée", value: 137 },
  { label: "Paraguay", value: 138 },
  { label: "Pays-Bas", value: 139 },
  { label: "Pérou", value: 140 },
  { label: "Philippines", value: 141 },
  { label: "Pologne", value: 142 },
  { label: "Portugal", value: 143 },
  { label: "Qatar", value: 144 },
  { label: "République centrafricaine", value: 145 },
  { label: "République dominicaine", value: 146 },
  { label: "République tchèque", value: 147 },
  { label: "Roumanie", value: 148 },
  { label: "Royaume-Uni", value: 149 },
  { label: "Russie", value: 150 },
  { label: "Rwanda", value: 151 },
  { label: "Saint-Kitts-et-Nevis", value: 152 },
  { label: "Saint-Marin", value: 153 },
  { label: "Saint-Vincent-et-les-Grenadines", value: 154 },
  { label: "Sainte-Lucie", value: 155 },
  { label: "Salvador", value: 156 },
  { label: "Samoa", value: 157 },
  { label: "Sao Tomé-et-Principe", value: 158 },
  { label: "Sénégal", value: 159 },
  { label: "Serbie", value: 160 },
  { label: "Seychelles", value: 161 },
  { label: "Sierra Leone", value: 162 },
  { label: "Singapour", value: 163 },
  { label: "Slovaquie", value: 164 },
  { label: "Slovénie", value: 165 },
  { label: "Somalie", value: 166 },
  { label: "Soudan", value: 167 },
  { label: "Soudan du Sud", value: 168 },
  { label: "Sri Lanka", value: 169 },
  { label: "Suède", value: 170 },
  { label: "Suisse", value: 171 },
  { label: "Suriname", value: 172 },
  { label: "Syrie", value: 173 },
  { label: "Tadjikistan", value: 174 },
  { label: "Tanzanie", value: 175 },
  { label: "Tchad", value: 176 },
  { label: "Thaïlande", value: 177 },
  { label: "Timor oriental", value: 178 },
  { label: "Togo", value: 179 },
  { label: "Tonga", value: 180 },
  { label: "Trinité-et-Tobago", value: 181 },
  { label: "Tunisie", value: 182 },
  { label: "Turkménistan", value: 183 },
  { label: "Turquie", value: 184 },
  { label: "Tuvalu", value: 185 },
  { label: "Ukraine", value: 186 },
  { label: "Uruguay", value: 187 },
  { label: "Vanuatu", value: 188 },
  { label: "Vatican", value: 189 },
  { label: "Venezuela", value: 190 },
  { label: "Viêt Nam", value: 191 },
  { label: "Yémen", value: 192 },
  { label: "Zambie", value: 193 },
  { label: "Zimbabwe", value: 194 },
];

export const countryListEn = [
  { label: "--Select a country--", value: -1 },
  { label: "Afghanistan", value: 1 },
  { label: "South Africa", value: 2 },
  { label: "Albania", value: 3 },
  { label: "Algeria", value: 4 },
  { label: "Germany", value: 5 },
  { label: "Andorra", value: 6 },
  { label: "Angola", value: 7 },
  { label: "Antigua and Barbuda", value: 8 },
  { label: "Saudi Arabia", value: 9 },
  { label: "Argentina", value: 10 },
  { label: "Armenia", value: 11 },
  { label: "Australia", value: 12 },
  { label: "Austria", value: 13 },
  { label: "Azerbaijan", value: 14 },
  { label: "Bahamas", value: 15 },
  { label: "Bahrain", value: 16 },
  { label: "Bangladesh", value: 17 },
  { label: "Barbados", value: 18 },
  { label: "Belgium", value: 19 },
  { label: "Belize", value: 20 },
  { label: "Benin", value: 21 },
  { label: "Bhutan", value: 22 },
  { label: "Belarus", value: 23 },
  { label: "Bolivia", value: 24 },
  { label: "Bosnia and Herzegovina", value: 25 },
  { label: "Botswana", value: 26 },
  { label: "Brazil", value: 27 },
  { label: "Brunei", value: 28 },
  { label: "Bulgaria", value: 29 },
  { label: "Burkina Faso", value: 30 },
  { label: "Burundi", value: 31 },
  { label: "Cambodia", value: 32 },
  { label: "Cameroon", value: 33 },
  { label: "Canada", value: 34 },
  { label: "Cape Verde", value: 35 },
  { label: "Chile", value: 36 },
  { label: "China", value: 37 },
  { label: "Cyprus", value: 38 },
  { label: "Colombia", value: 39 },
  { label: "Comoros", value: 40 },
  { label: "Republic of the Congo", value: 41 },
  { label: "Democratic Republic of the Congo", value: 42 },
  { label: "North Korea", value: 43 },
  { label: "South Korea", value: 44 },
  { label: "Costa Rica", value: 45 },
  { label: "Ivory Coast", value: 46 },
  { label: "Croatia", value: 47 },
  { label: "Cuba", value: 48 },
  { label: "Denmark", value: 49 },
  { label: "Djibouti", value: 50 },
  { label: "Dominica", value: 51 },
  { label: "Egypt", value: 52 },
  { label: "United Arab Emirates", value: 53 },
  { label: "Ecuador", value: 54 },
  { label: "Eritrea", value: 55 },
  { label: "Spain", value: 56 },
  { label: "Estonia", value: 57 },
  { label: "Eswatini", value: 58 },
  { label: "United States", value: 59 },
  { label: "Ethiopia", value: 60 },
  { label: "Fiji", value: 61 },
  { label: "Finland", value: 62 },
  { label: "France", value: 63 },
  { label: "Gabon", value: 64 },
  { label: "Gambia", value: 65 },
  { label: "Georgia", value: 66 },
  { label: "Ghana", value: 67 },
  { label: "Greece", value: 68 },
  { label: "Grenada", value: 69 },
  { label: "Guatemala", value: 70 },
  { label: "Guinea", value: 71 },
  { label: "Guinea-Bissau", value: 72 },
  { label: "Equatorial Guinea", value: 73 },
  { label: "Guyana", value: 74 },
  { label: "Haiti", value: 75 },
  { label: "Honduras", value: 76 },
  { label: "Hungary", value: 77 },
  { label: "Marshall Islands", value: 78 },
  { label: "Solomon Islands", value: 79 },
  { label: "India", value: 80 },
  { label: "Indonesia", value: 81 },
  { label: "Iraq", value: 82 },
  { label: "Iran", value: 83 },
  { label: "Ireland", value: 84 },
  { label: "Iceland", value: 85 },
  { label: "Israel", value: 86 },
  { label: "Italy", value: 87 },
  { label: "Jamaica", value: 88 },
  { label: "Japan", value: 89 },
  { label: "Jordan", value: 90 },
  { label: "Kazakhstan", value: 91 },
  { label: "Kenya", value: 92 },
  { label: "Kyrgyzstan", value: 93 },
  { label: "Kiribati", value: 94 },
  { label: "Kuwait", value: 95 },
  { label: "Laos", value: 96 },
  { label: "Lesotho", value: 97 },
  { label: "Latvia", value: 98 },
  { label: "Lebanon", value: 99 },
  { label: "Liberia", value: 100 },
  { label: "Libya", value: 101 },
  { label: "Liechtenstein", value: 102 },
  { label: "Lithuania", value: 103 },
  { label: "Luxembourg", value: 104 },
  { label: "North Macedonia", value: 105 },
  { label: "Madagascar", value: 106 },
  { label: "Malaysia", value: 107 },
  { label: "Malawi", value: 108 },
  { label: "Maldives", value: 109 },
  { label: "Mali", value: 110 },
  { label: "Malta", value: 111 },
  { label: "Morocco", value: 112 },
  { label: "Mauritius", value: 113 },
  { label: "Mauritania", value: 114 },
  { label: "Mexico", value: 115 },
  { label: "Micronesia", value: 116 },
  { label: "Moldova", value: 117 },
  { label: "Monaco", value: 118 },
  { label: "Mongolia", value: 119 },
  { label: "Montenegro", value: 120 },
  { label: "Mozambique", value: 121 },
  { label: "Myanmar", value: 122 },
  { label: "Namibia", value: 123 },
  { label: "Nauru", value: 124 },
  { label: "Nepal", value: 125 },
  { label: "Nicaragua", value: 126 },
  { label: "Niger", value: 127 },
  { label: "Nigeria", value: 128 },
  { label: "Norway", value: 129 },
  { label: "New Zealand", value: 130 },
  { label: "Oman", value: 131 },
  { label: "Uganda", value: 132 },
  { label: "Uzbekistan", value: 133 },
  { label: "Pakistan", value: 134 },
  { label: "Palau", value: 135 },
  { label: "Panama", value: 136 },
  { label: "Papua New Guinea", value: 137 },
  { label: "Paraguay", value: 138 },
  { label: "Netherlands", value: 139 },
  { label: "Peru", value: 140 },
  { label: "Philippines", value: 141 },
  { label: "Poland", value: 142 },
  { label: "Portugal", value: 143 },
  { label: "Qatar", value: 144 },
  { label: "Central African Republic", value: 145 },
  { label: "Dominican Republic", value: 146 },
  { label: "Czech Republic", value: 147 },
  { label: "Romania", value: 148 },
  { label: "United Kingdom", value: 149 },
  { label: "Russia", value: 150 },
  { label: "Rwanda", value: 151 },
  { label: "Saint Kitts and Nevis", value: 152 },
  { label: "San Marino", value: 153 },
  { label: "Saint Vincent and the Grenadines", value: 154 },
  { label: "Saint Lucia", value: 155 },
  { label: "El Salvador", value: 156 },
  { label: "Samoa", value: 157 },
  { label: "Sao Tome and Principe", value: 158 },
  { label: "Senegal", value: 159 },
  { label: "Serbia", value: 160 },
  { label: "Seychelles", value: 161 },
  { label: "Sierra Leone", value: 162 },
  { label: "Singapore", value: 163 },
  { label: "Slovakia", value: 164 },
  { label: "Slovenia", value: 165 },
  { label: "Somalia", value: 166 },
  { label: "Sudan", value: 167 },
  { label: "South Sudan", value: 168 },
  { label: "Sri Lanka", value: 169 },
  { label: "Sweden", value: 170 },
  { label: "Switzerland", value: 171 },
  { label: "Suriname", value: 172 },
  { label: "Syria", value: 173 },
  { label: "Tajikistan", value: 174 },
  { label: "Tanzania", value: 175 },
  { label: "Chad", value: 176 },
  { label: "Thailand", value: 177 },
  { label: "East Timor", value: 178 },
  { label: "Togo", value: 179 },
  { label: "Tonga", value: 180 },
  { label: "Trinidad and Tobago", value: 181 },
  { label: "Tunisia", value: 182 },
  { label: "Turkmenistan", value: 183 },
  { label: "Turkey", value: 184 },
  { label: "Tuvalu", value: 185 },
  { label: "Ukraine", value: 186 },
  { label: "Uruguay", value: 187 },
  { label: "Vanuatu", value: 188 },
  { label: "Vatican City", value: 189 },
  { label: "Venezuela", value: 190 },
  { label: "Vietnam", value: 191 },
  { label: "Yemen", value: 192 },
  { label: "Zambia", value: 193 },
  { label: "Zimbabwe", value: 194 },
];
